from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
R=ROOT/'ops/x100/receipts/bootstrap'
R.mkdir(parents=True,exist_ok=True)
def wr(name,world,claim,branch,pr,evidence):
    obj={"schema_version":1,"receipt_id":name,"world_id":world,"claim_id":claim,"branch":branch,"source_kind":"BOOTSTRAP_FROM_PR_EVIDENCE","evidence":[{"dimension":d,"cell":c,"maturity":m,"evidence_refs":[pr]} for d,c,m in evidence]}
    (R/(name+'.json')).write_text(json.dumps(obj,indent=2)+"\n")
wr('X100-BOOT-TERRA-PR1','terra','CLM-TERRA-RELIQUARY-KIT-001','art/terra-reliquary-kit-001','https://github.com/rotprods/-/pull/1',[('meso_architecture','industrial','locally_validated'),('micro_assets','machinery','locally_validated'),('material_causality','material_families','empirically_qualified'),('optimization','collision','empirically_qualified'),('qa','geometry_uv_material','locally_validated'),('qa','engine_runtime','empirically_qualified'),('reusability','modular_kits','implemented')])
wr('X100-BOOT-KHEPRI-PR8','khepri','CLM-KHEPRI-WMACRO-001','art/world-khepri-001','https://github.com/rotprods/-/pull/8',[('macro_world','regional_layout','empirically_qualified'),('macro_world','transport_network','locally_validated'),('micro_assets','machinery','systemic_complete'),('gameplay','traversal','implemented'),('variation','configuration','systemic_complete'),('variation','temporal','systemic_complete'),('optimization','lod','locally_validated'),('optimization','instancing_drawcalls','empirically_qualified'),('reusability','procedural_generators','systemic_complete'),('reusability','placement_rules','systemic_complete'),('qa','geometry_uv_material','empirically_qualified'),('qa','engine_runtime','empirically_qualified')])
wr('X100-BOOT-SYLVA-MACRO-PR3','sylva','CLM-SYLVA-MACRO-001','art/world-sylva-prime-macro-001','https://github.com/rotprods/-/pull/3',[('macro_world','regional_layout','systemic_complete'),('macro_world','transport_network','locally_validated'),('gameplay','traversal','locally_validated'),('optimization','collision','locally_validated'),('optimization','streaming','locally_validated'),('qa','geometry_uv_material','empirically_qualified'),('storytelling','current_state','implemented')])
wr('X100-BOOT-SYLVA-ROOT-PR6','sylva','CLM-SYLVA-PROC-NROOT-001','agent/sylva-neural-root-001','https://github.com/rotprods/-/pull/6',[('meso_architecture','utilities_infrastructure','locally_validated'),('micro_assets','machinery','implemented'),('reusability','modular_kits','locally_validated'),('reusability','procedural_generators','locally_validated'),('optimization','collision','locally_validated'),('qa','geometry_uv_material','locally_validated')])
wr('X100-BOOT-UMBRA-PR16','umbra','CLM-W04-WORLD-UMBRA-001','art/world-umbra-001','https://github.com/rotprods/-/pull/16',[('macro_world','regional_layout','locally_validated'),('meso_architecture','settlement_logic','locally_validated'),('gameplay','traversal','implemented'),('storytelling','current_state','locally_validated'),('optimization','instancing_drawcalls','locally_validated'),('qa','geometry_uv_material','empirically_qualified')])
wr('X100-BOOT-NACRE-PR17','nacre','CLM-NACRE-WORLD-MACRO-001','art/world-nacre-001','https://github.com/rotprods/-/pull/17',[('macro_world','regional_layout','locally_validated'),('meso_architecture','utilities_infrastructure','locally_validated'),('gameplay','traversal','implemented'),('material_causality','manufacturing_response','implemented'),('optimization','collision','locally_validated'),('reusability','procedural_generators','empirically_qualified'),('qa','geometry_uv_material','empirically_qualified'),('qa','canon','locally_validated')])
wr('X100-BOOT-PELAGOS-PR5','pelagos','CLM-PEL-WORLD-001','art/world-pelagos-thalassa-001','https://github.com/rotprods/-/pull/5',[('macro_world','regional_layout','locally_validated'),('meso_architecture','settlement_logic','locally_validated'),('meso_architecture','utilities_infrastructure','locally_validated'),('micro_assets','machinery','locally_validated'),('ecology','fauna','locally_validated'),('ecology','habitats','implemented'),('civilization','mobility','locally_validated'),('material_causality','material_families','locally_validated'),('variation','temporal','systemic_complete'),('optimization','lod','locally_validated'),('optimization','collision','locally_validated'),('reusability','procedural_generators','systemic_complete'),('qa','geometry_uv_material','locally_validated')])
wr('X100-BOOT-VANTA-PR4','vanta','CLM-VANTA-WORLD-001','art/world-vanta-001','https://github.com/rotprods/-/pull/4',[('macro_world','regional_layout','locally_validated'),('meso_architecture','utilities_infrastructure','locally_validated'),('micro_assets','machinery','locally_validated'),('gameplay','traversal','empirically_qualified'),('material_causality','material_families','empirically_qualified'),('optimization','collision','empirically_qualified'),('optimization','instancing_drawcalls','locally_validated'),('qa','geometry_uv_material','empirically_qualified'),('qa','engine_runtime','empirically_qualified')])
wr('X100-BOOT-ELYSIUM-PR15','elysium','OBS-ELYSIUM-001','art/world-elysium-null-001','https://github.com/rotprods/-/pull/15',[('macro_world','regional_layout','locally_validated'),('meso_architecture','settlement_logic','locally_validated'),('meso_architecture','residential','locally_validated'),('variation','configuration','locally_validated'),('gameplay','puzzle','implemented'),('reusability','modular_kits','locally_validated'),('qa','geometry_uv_material','empirically_qualified')])
wr('X100-BOOT-LEVIATHAN-PR10','leviathan','CLM-W10-WORLD-LEVIATHAN-001','art/world-leviathan-001','https://github.com/rotprods/-/pull/10',[('macro_world','regional_layout','locally_validated'),('meso_architecture','settlement_logic','locally_validated'),('meso_architecture','utilities_infrastructure','locally_validated'),('micro_assets','machinery','implemented'),('ecology','flora','implemented'),('gameplay','traversal','locally_validated'),('material_causality','material_families','empirically_qualified'),('optimization','instancing_drawcalls','locally_validated'),('optimization','lod','planned'),('reusability','procedural_generators','locally_validated'),('qa','geometry_uv_material','empirically_qualified')])
wr('X100-BOOT-AURORA-PR20','aurora','CLM-AURORA-WORLD-001','art/world-aurora-veil-001','https://github.com/rotprods/-/pull/20',[('macro_world','planetary_representation','locally_validated'),('macro_world','regional_layout','locally_validated'),('macro_world','landmarks_vistas','locally_validated'),('meso_architecture','settlement_logic','implemented'),('ecology','flora','implemented'),('ecology','fauna','implemented'),('optimization','collision','implemented'),('optimization','streaming','implemented'),('qa','geometry_uv_material','locally_validated')])
wr('X100-BOOT-ORIGIN-PR18','origin','CLM-ORIGIN-MEGA-ATRIO-001','art/world-origin-001','https://github.com/rotprods/-/pull/18',[('meso_architecture','utilities_infrastructure','locally_validated'),('gameplay','traversal','implemented'),('material_causality','material_families','implemented'),('optimization','collision','locally_validated'),('reusability','modular_kits','locally_validated'),('qa','geometry_uv_material','empirically_qualified')])
print(json.dumps({'written':len(list(R.glob('*.json'))),'out':str(R.relative_to(ROOT))}))
