"""Optimization pass for EXOVANT KHEPRI world-macro blockout.

Input contract: scene generated by generate_khepri_world_macro.py.
Output contract: identical visual/transform layout, but repeated heliostat mast geometry
shares one mesh datablock. This keeps the first blockout reproducible without silently
changing cross-domain asset ownership.
"""
import bpy

PREFIX = "KHP_WM_HELIOSTAT_MAST_"
masts = sorted([o for o in bpy.data.objects if o.type == "MESH" and o.name.startswith(PREFIX)], key=lambda o: o.name)
if not masts:
    raise RuntimeError("No KHEPRI heliostat mast proxies found; run generator first")

shared = masts[0].data
shared.name = "KHP_WM_SHARED_HELIOSTAT_MAST"
for obj in masts[1:]:
    obj.data = shared

for mesh in list(bpy.data.meshes):
    if mesh.users == 0:
        bpy.data.meshes.remove(mesh)

result = {
    "mast_objects": len(masts),
    "mast_unique_meshes": len({id(o.data) for o in masts}),
    "shared_mesh": shared.name,
}
print(result)
